"""Installer registry-data step (#1643 W5c, Amendment F: TD-D54..TD-D57).

Covers T5.33, T5.44, T5.47 (install half), T5.69, T5.70, T5.71, T5.72.

Install-driven tests run the real ``bootstrap/hos_install.sh --local`` (about
5 s each) and are ``@pytest.mark.slow`` with one module-scoped fixture per
install configuration (TD-D58). T5.44 and T5.71 are static and unmarked.
"""

from __future__ import annotations

import hashlib
import os
import re
import subprocess
from pathlib import Path

import pytest

from scripts.automation.lib import dimension_registry as dr
from tests.tmp_hygiene import child_env

ROOT = Path(__file__).resolve().parents[2]
INSTALL_SH = ROOT / "bootstrap" / "hos_install.sh"

# §C.2.5, verbatim.
RESOLVED_PACKS_HEADER = (
    "# Generated by bootstrap/hos_install.sh — the resolved pack closure, deps first. "
    "Do not edit; re-run the installer."
)
GITATTRIBUTES_LINES = (
    "contract/dimensions/** -text",
    "contract/resolved-packs.txt -text",
    ".hos-manifest -text",
)


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #


def _git(target: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(target), "-c", "commit.gpgsign=false", *args],
        capture_output=True,
        text=True,
        check=check,
    )


def _git_init_target(base: Path) -> Path:
    target = base / "target"
    target.mkdir()
    subprocess.run(["git", "init", str(target)], capture_output=True, check=True)
    _git(target, "config", "user.email", "test@example.com")
    _git(target, "config", "user.name", "Test")
    return target


def _run_installer(target: Path, *extra_args: str) -> subprocess.CompletedProcess:
    env = {**os.environ, "HOS_NO_CONFIG": "1"}
    return subprocess.run(
        ["bash", str(INSTALL_SH), "--local", str(target), *extra_args],
        capture_output=True,
        text=True,
        env=child_env(env),
        input="\n",
    )


def _install_ok(target: Path, *extra_args: str) -> subprocess.CompletedProcess:
    r = _run_installer(target, *extra_args)
    assert r.returncode == 0, r.stdout + r.stderr
    return r


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _manifest_rows(target: Path) -> list[list[str]]:
    rows = []
    for line in (target / ".hos-manifest").read_text(encoding="utf-8").splitlines():
        if line and not line.startswith("#"):
            rows.append(line.split("\t"))
    return rows


def _whole_rows_for(target: Path, path: str) -> list[list[str]]:
    return [r for r in _manifest_rows(target) if r[0] == path and r[1] == "WHOLE"]


def _gitattributes_lines(target: Path) -> list[str]:
    return (target / ".gitattributes").read_text(encoding="utf-8").splitlines()


def _commit_all(target: Path) -> None:
    _git(target, "add", "-A")
    _git(target, "commit", "-q", "-m", "install")


def _recheckout_with_autocrlf(target: Path) -> None:
    """Simulate a fresh clone on an autocrlf=true machine."""
    _git(target, "config", "core.autocrlf", "true")
    subprocess.run(
        ["rm", "-rf", str(target / "contract"), str(target / ".hos-manifest")], check=True
    )
    _git(target, "checkout", "--", ".")


# --------------------------------------------------------------------------- #
# module-scoped install fixtures, one per configuration
# --------------------------------------------------------------------------- #


@pytest.fixture(scope="module")
def django_install(tmp_path_factory):
    target = _git_init_target(tmp_path_factory.mktemp("django"))
    r = _install_ok(target, "--pack", "django")
    return target, r


@pytest.fixture(scope="module")
def django_then_astro(tmp_path_factory):
    target = _git_init_target(tmp_path_factory.mktemp("django_astro"))
    _install_ok(target, "--pack", "django")
    r = _install_ok(target, "--pack", "astro")
    return target, r


@pytest.fixture(scope="module")
def no_pack_install(tmp_path_factory):
    target = _git_init_target(tmp_path_factory.mktemp("nopack"))
    _install_ok(target, "--no-pack")
    return target


@pytest.fixture(scope="module")
def astro_planted(tmp_path_factory):
    """astro closure includes `node`, which ships no dimensions.yaml (T5.70)."""
    target = _git_init_target(tmp_path_factory.mktemp("astro_planted"))
    _install_ok(target, "--pack", "astro")
    planted = target / "contract" / "dimensions" / "pack-node.yaml"
    planted.write_text("planted: true\n", encoding="utf-8")
    r = _install_ok(target, "--pack", "astro")
    return target, r


# --------------------------------------------------------------------------- #
# T5.44 — static
# --------------------------------------------------------------------------- #


def _installer_lines() -> list[str]:
    return INSTALL_SH.read_text(encoding="utf-8").splitlines()


def test_t5_44_registry_kinds_table_matches_engine():
    text = INSTALL_SH.read_text(encoding="utf-8")
    m = re.search(r"^_REGISTRY_KINDS=\(([^)]*)\)", text, re.M)
    assert m, "_REGISTRY_KINDS=( ... ) literal not found in hos_install.sh"
    rows = re.findall(r'"([^"]+)"', m.group(1))
    parsed = {tuple(row.split(":", 1)) for row in rows}
    assert len(parsed) == len(rows), "duplicate _REGISTRY_KINDS rows"
    assert parsed == {(k.pack_source, k.directory) for k in dr.KINDS.values()}


def test_t5_44_resolved_pack_dirs_appended_once_in_r3_loop():
    lines = _installer_lines()
    hits = [i for i, ln in enumerate(lines) if "_resolved_pack_dirs+=" in ln]
    assert len(hits) == 1, f"expected exactly one _resolved_pack_dirs+=, got {len(hits)}"
    i = hits[0]
    # The append sits in the R3 loop, directly after _resolve_pack_dir succeeds.
    loop_start = max(j for j in range(i) if lines[j].startswith("for _p in "))
    assert "_resolve_pack_dir" in "\n".join(lines[loop_start:i])
    assert "_resolved_packs" in lines[loop_start]


def test_t5_44_registry_block_never_calls_resolve_pack_dir():
    lines = _installer_lines()
    start = next(i for i, ln in enumerate(lines) if "registry data (ADR-1643 TD-D31/D32/D54)" in ln)
    end = next(i for i in range(start + 1, len(lines)) if lines[i].startswith("# ── audit/"))
    code = [ln for ln in lines[start:end] if not ln.lstrip().startswith("#")]
    assert not any("_resolve_pack_dir" in ln for ln in code)


# --------------------------------------------------------------------------- #
# T5.71 — static
# --------------------------------------------------------------------------- #


def test_t5_71_commit_hint_names_manifest_and_gitattributes():
    hint = [ln for ln in _installer_lines() if "scripts/ .github/ prompts/" in ln]
    assert len(hint) == 1
    assert ".hos-manifest" in hint[0]
    assert ".gitattributes" in hint[0]
    assert hint[0].index(".gitignore") < hint[0].index(".hos-manifest")


def test_t5_71_ensure_line_exact_scoping():
    calls = [
        ln.strip()
        for ln in _installer_lines()
        if re.match(r"\s*(\$ROLE_HUMAN && )?ensure_line\b", ln)
    ]
    # Multi-line calls: only the first physical line carries the target argument.
    gitignore = [c for c in calls if '"$GITIGNORE"' in c]
    gitattrs = [c for c in calls if "_GITATTRIBUTES" in c]
    assert len(gitignore) == 8
    assert len(gitattrs) == 3
    text = INSTALL_SH.read_text(encoding="utf-8")
    # A call spans to the first line not ending in a backslash continuation.
    for m in re.finditer(r"ensure_line\s+\"\$GITIGNORE\"(?:[^\n]*\\\n)*[^\n]*", text):
        assert not re.search(r"\bexact\b", m.group(0)), m.group(0)
    for c in gitattrs:
        assert c.endswith("exact"), c


# --------------------------------------------------------------------------- #
# T5.47 — install half
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_t5_47_resolved_packs_bytes_astro(django_then_astro):
    target, _ = django_then_astro
    got = (target / "contract" / "resolved-packs.txt").read_bytes()
    assert got == (RESOLVED_PACKS_HEADER + "\nnode\nastro\n").encode("utf-8")


@pytest.mark.slow
def test_t5_47_resolved_packs_bytes_no_pack(no_pack_install):
    got = (no_pack_install / "contract" / "resolved-packs.txt").read_bytes()
    assert got == (RESOLVED_PACKS_HEADER + "\n").encode("utf-8")


@pytest.mark.slow
def test_t5_47_one_copy_log_line_per_pack(django_install):
    _, r = django_install
    needle = "contract/dimensions/pack-django.yaml (framework — updated)"
    assert sum(needle in ln for ln in (r.stdout + r.stderr).splitlines()) == 1


@pytest.mark.slow
def test_t5_47_manifest_rows(django_install):
    target, _ = django_install
    for rel in ("contract/dimensions/pack-django.yaml", "contract/resolved-packs.txt"):
        rows = _whole_rows_for(target, rel)
        assert len(rows) == 1, (rel, rows)
        assert rows[0][2] == _sha(target / rel)
    core = _whole_rows_for(target, "contract/dimensions/core.yaml")
    assert len(core) == 1
    assert core[0][2] == _sha(ROOT / "contract" / "dimensions" / "core.yaml")
    assert not [
        r for r in _manifest_rows(target) if r[0] == "scripts/framework/run_post_change_sweep.sh"
    ]


@pytest.mark.slow
def test_t5_47_absent_and_not_hos_copy(django_install):
    target, _ = django_install
    assert not (target / "contract" / "dimensions" / "project.yaml").exists()
    assert not (target / "scripts" / "framework" / "run_post_change_sweep.sh").exists()
    text = (target / "contract" / "resolved-packs.txt").read_text(encoding="utf-8")
    assert text.startswith(RESOLVED_PACKS_HEADER)


@pytest.mark.slow
def test_t5_47_load_green_after_install(django_install):
    target, _ = django_install
    reg = dr.load(target)
    assert len(reg.entries) == 17
    assert len(reg.bindings) == 23
    assert reg.packs == ("django",)


@pytest.mark.slow
def test_t5_47_drift_blocked_install_writes_no_registry_data(tmp_path):
    target = _git_init_target(tmp_path)
    _install_ok(target, "--pack", "django")
    agent = target / ".claude" / "agents" / "code-reviewer.md"
    original = agent.read_bytes()
    marker = b"<!-- HOS:PACK:django:START -->"
    assert marker in original, "PACK:django region marker not found in code-reviewer.md"
    start = original.index(marker) + len(marker)
    edited = original[:start] + b"\nCONSUMER EDITED PACK BODY\n" + original[start:]
    agent.write_bytes(edited)
    pack_file = target / "contract" / "dimensions" / "pack-django.yaml"
    pack_file.unlink()
    resolved = target / "contract" / "resolved-packs.txt"
    resolved_before = resolved.read_bytes()

    r = _run_installer(target, "--pack", "django")
    assert r.returncode == 4, r.stdout + r.stderr
    assert resolved.read_bytes() == resolved_before, "aborted install rewrote resolved-packs.txt"
    assert not pack_file.exists(), "Phase A abort must precede the registry-data step"


# --------------------------------------------------------------------------- #
# T5.33 — re-install with a different pack
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_t5_33_pack_switch_prunes_and_reloads(django_then_astro):
    target, r = django_then_astro
    dims = target / "contract" / "dimensions"
    assert not (dims / "pack-django.yaml").exists()
    assert "contract/dimensions/pack-django.yaml removed — pack 'django' is no longer resolved" in (
        r.stdout + r.stderr
    )
    assert (dims / "pack-astro.yaml").read_bytes() == (
        ROOT / "packs" / "astro" / "dimensions.yaml"
    ).read_bytes()
    assert dr.load(target).packs == ("node", "astro")


# --------------------------------------------------------------------------- #
# T5.70 — leftover file for a resolved pack that ships no dimensions.yaml
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_t5_70_leftover_for_resolved_pack_without_data_removed(astro_planted):
    target, r = astro_planted
    assert not (target / "contract" / "dimensions" / "pack-node.yaml").exists()
    assert "pack 'node' ships no dimensions.yaml" in (r.stdout + r.stderr)
    assert not _whole_rows_for(target, "contract/dimensions/pack-node.yaml")
    assert dr.load(target).packs == ("node", "astro")


# --------------------------------------------------------------------------- #
# T5.69 — .gitattributes (-text) and the autocrlf false installed_drift
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_t5_69_gitattributes_lines_once_and_idempotent(tmp_path):
    target = _git_init_target(tmp_path)
    _install_ok(target, "--pack", "django")
    for line in GITATTRIBUTES_LINES:
        assert _gitattributes_lines(target).count(line) == 1
    _install_ok(target, "--pack", "django")
    for line in GITATTRIBUTES_LINES:
        assert _gitattributes_lines(target).count(line) == 1


@pytest.mark.slow
def test_t5_69_autocrlf_checkout_stays_green_and_control_drifts(tmp_path):
    target = _git_init_target(tmp_path)
    _install_ok(target, "--pack", "django")
    _commit_all(target)
    _recheckout_with_autocrlf(target)
    assert dr.load(target).packs == ("django",)
    attr = _git(target, "check-attr", "text", "--", "contract/dimensions/prompts/ui.md").stdout
    assert attr.strip().endswith("text: unset")

    # Control: without the attributes, the same re-checkout must drift.
    _git(target, "config", "core.autocrlf", "false")
    (target / ".gitattributes").write_text("", encoding="utf-8")
    _git(target, "add", "-A")
    _git(target, "commit", "-q", "-m", "drop attributes")
    _recheckout_with_autocrlf(target)
    # Without -text the checkout rewrote the HOS-hashed files to CRLF.
    assert b"\r\n" in (target / "contract" / "resolved-packs.txt").read_bytes()
    assert b"\r\n" in (target / "contract" / "dimensions" / "core.yaml").read_bytes()
    # L24 parses resolved-packs.txt before L31 hashes it, so "invalid pack slug"
    # is the first failure under CRLF (TD-VF-39's installed_drift expectation is
    # pre-empted); this proves the green case above discriminates.
    with pytest.raises(dr.RegistryError, match="invalid pack slug"):
        dr.load(target)


@pytest.mark.slow
def test_t5_69_missing_final_newline_and_near_miss_line(tmp_path):
    target = _git_init_target(tmp_path)
    (target / ".gitattributes").write_bytes(b"#.hos-manifest -text\n*.png binary")
    _install_ok(target, "--pack", "django")
    lines = _gitattributes_lines(target)
    assert "*.png binary" in lines
    assert "#.hos-manifest -text" in lines
    for line in GITATTRIBUTES_LINES:
        assert lines.count(line) == 1, (line, lines)
    attr = _git(target, "check-attr", "binary", "--", "x.png").stdout
    assert attr.strip().endswith("binary: set")


# --------------------------------------------------------------------------- #
# T5.72 — dry run
# --------------------------------------------------------------------------- #


@pytest.mark.slow
def test_t5_72_dry_run_writes_nothing_and_previews(tmp_path):
    target = _git_init_target(tmp_path)
    r = _run_installer(target, "--dry-run", "--pack", "django")
    assert r.returncode == 0, r.stdout + r.stderr
    assert not (target / "contract" / "dimensions").exists()
    assert not (target / "contract" / "resolved-packs.txt").exists()
    assert not (target / ".gitattributes").exists()
    lines = r.stdout.splitlines()
    idx = next(i for i, ln in enumerate(lines) if "Would write contract/resolved-packs.txt:" in ln)
    assert any(ln.strip().endswith("django") for ln in lines[idx + 1 : idx + 4])
