"""Freshness test for SCRIPTS-INDEX.md (#1214).

SCRIPTS-INDEX.md is GENERATED by scripts/framework/gen_scripts_index.sh from the
actual script inventory under bin/ (top-level), bootstrap/ (top-level), and
scripts/ (recursive). If a script is added, removed, or renamed without
regenerating the index, this test fails — mirroring the CODEOWNERS-generation
guard pattern (see tests/framework/test_consumer_framework_files.py, which
guards the analogous framework_consumer_files.txt / hos_install.sh pairing).
"""
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATOR = ROOT / "scripts" / "framework" / "gen_scripts_index.sh"
INDEX = ROOT / "SCRIPTS-INDEX.md"

_SCAN_CMD = (
    "find bin -maxdepth 1 -type f; "
    "find bootstrap -maxdepth 1 -type f -name '*.sh'; "
    "find scripts \\( -path '*/.venv' -o -path '*/__pycache__' \\) -prune "
    "-o -type f \\( -name '*.sh' -o -name '*.py' \\) -print"
)


def _current_script_files():
    """Independent re-scan of the same three roots the generator scans, so this
    test does not simply trust the generator's own enumeration."""
    result = subprocess.run(
        ["bash", "-c", _SCAN_CMD], cwd=ROOT, check=True, capture_output=True, text=True
    )
    return [line.lstrip("./") for line in result.stdout.splitlines() if line.strip()]


def test_generator_and_index_exist():
    assert GENERATOR.is_file(), "scripts/framework/gen_scripts_index.sh is missing"
    assert INDEX.is_file(), "SCRIPTS-INDEX.md is missing — run gen_scripts_index.sh"


def test_index_matches_generator_output(tmp_path):
    """Regenerate into a temp path (never touching the committed file) and diff
    byte-for-byte against what's checked in."""
    out = tmp_path / "SCRIPTS-INDEX.md"
    subprocess.run(
        ["bash", str(GENERATOR), str(out)], cwd=ROOT, check=True, capture_output=True, text=True
    )
    generated = out.read_text()
    committed = INDEX.read_text()
    assert generated == committed, (
        "SCRIPTS-INDEX.md is stale relative to scripts/, bootstrap/, bin/ — "
        "regenerate with: scripts/framework/gen_scripts_index.sh"
    )


def test_every_script_file_appears_in_index():
    """Minimum floor, independent of the exact-match test above: every current
    script under the scanned roots is named somewhere in the committed index.
    __init__.py package markers are deliberately excluded by the generator
    (they carry no invocable content)."""
    content = INDEX.read_text()
    missing = [
        rel
        for rel in _current_script_files()
        if Path(rel).name != "__init__.py" and rel not in content
    ]
    assert not missing, (
        f"Files missing from SCRIPTS-INDEX.md: {missing} — "
        "regenerate with scripts/framework/gen_scripts_index.sh"
    )
