"""Freshness test for .github/CODEOWNERS (#1414).

.github/CODEOWNERS is GENERATED by scripts/framework/gen_codeowners.sh from
scripts/framework/protected_surfaces.txt (the canonical protected-surface list,
AGENT-IDENTITY.md §9). If a surface is added, removed, or reworded in
protected_surfaces.txt without regenerating CODEOWNERS, the human-approval gate
and the generated file silently disagree about which paths require a human code
owner — the governance-critical drift #1414 flagged as previously unguarded.
Mirrors the pattern in test_scripts_index.py.
"""
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GENERATOR = ROOT / "scripts" / "framework" / "gen_codeowners.sh"
SURFACES = ROOT / "scripts" / "framework" / "protected_surfaces.txt"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"


def _committed_owner() -> str:
    """Extract the owner the committed file was generated with (the '# Owner:
    @X' line), so regeneration doesn't depend on a network call to `gh`."""
    match = re.search(r"^# Owner: (@\S+)$", CODEOWNERS.read_text(), flags=re.MULTILINE)
    assert match, "committed CODEOWNERS has no '# Owner: @X' line to regenerate against"
    return match.group(1)


def _regenerate(tmp_path: Path, owner: str) -> str:
    """Run gen_codeowners.sh inside an isolated copy of the repo layout it
    depends on, so the real .github/CODEOWNERS is never touched. The script
    resolves REPO_ROOT from its own on-disk location and writes to
    "$REPO_ROOT/.github/CODEOWNERS", so both must live under tmp_path."""
    fw_dir = tmp_path / "scripts" / "framework"
    fw_dir.mkdir(parents=True)
    shutil.copy(GENERATOR, fw_dir / GENERATOR.name)
    shutil.copy(SURFACES, fw_dir / SURFACES.name)
    (tmp_path / ".github").mkdir()
    subprocess.run(
        ["bash", str(fw_dir / GENERATOR.name), owner],
        cwd=tmp_path,
        check=True,
        capture_output=True,
        text=True,
    )
    return (tmp_path / ".github" / "CODEOWNERS").read_text()


def test_generator_and_files_exist():
    assert GENERATOR.is_file(), "scripts/framework/gen_codeowners.sh is missing"
    assert SURFACES.is_file(), "scripts/framework/protected_surfaces.txt is missing"
    assert CODEOWNERS.is_file(), ".github/CODEOWNERS is missing — run gen_codeowners.sh"


def test_codeowners_matches_generator_output(tmp_path):
    owner = _committed_owner()
    regenerated = _regenerate(tmp_path, owner)
    committed = CODEOWNERS.read_text()
    assert regenerated == committed, (
        ".github/CODEOWNERS is stale relative to protected_surfaces.txt — "
        f"regenerate with: scripts/framework/gen_codeowners.sh {owner}"
    )
