#!/usr/bin/env python3
"""select_work_candidates.py — the deterministic, author-trust-gated
work-selection entry point (S2 of #1540, fix path for #1539).

Protected surface. AD-3's single entry point: query + trust + authorization +
ordering. This is the ONLY way work candidates are produced — both
`bin/hos-cron`'s pre-computed context block and `bootstrap/worker-cron-prompt.md`
Step 2's fallback invoke this exact command (§2.4, §2.5 of
docs/v0.7.0/TECHNICAL-DESIGN-1540-S1-S2-intake-trust-gate.md, revision 8).

It never writes to GitHub — no labels, no comments, no state, no cache, no
resume cursor (FR7/AD-4: every cycle re-derives from live state).

Exit codes (§2.2, AM-32):
  0 = a determination the gate can STATE the extent of, with at least one
      candidate emitted OR with `complete=yes`.
  3 = DEGRADED. `complete=no` AND stdout EMPTY. The gate ran, could not
      finish looking, and is saying so rather than claiming an empty queue.
      NOT an error, NOT fail-closed.
  2 = fail closed. stdout EMPTY. Exactly one `select_work_candidates: <token>`
      line on stderr (plus a remediation line for the four F1/F2/F3/F4 rows).

The algorithm's order is part of the contract (§2.3, AM-19/AM-29):
  A args -> B config (incl. LAZY tier resolution) -> C list (PAGINATED)
  D1 drop PR records (free) -> D2 drop EXCLUDED_LABELS (free)
  D3 requester_verdict (free) -> D4 trusted -> eligible, zero cost (free)
  D-rank: rank the WHOLE set (free) -- precedes D5, never move it below
  D5: walk the ranked list; pay per untrusted record (events query)
  E: sort the admitted set into emission order -> F: report

Two orders, deliberately different (AM-29, TP-1):
  WALK  = (rank, number DESC)  -- a reachability decision, total by
          construction (issue numbers are unique; no tie-break needed).
  EMIT  = (rank, number ASC)   -- #901's documented FIFO-within-band.

Every bounded list fetch in this module issues ONE `gh api` invocation PER
PAGE, with `page=` and `per_page=100` literally in the endpoint's query
string -- never `--paginate` (which on gh 2.45.0 fetches every page with no
cap and cannot be stopped by a request-budget stop test) and never `-f`/`-F`
(which silently switches the request method to POST). A page shorter than
100 raw items ends the history (§1.4's per-page fetch rule, revision 8 /
RP5-1). No `--repo-root` flag exists (AD-13): the repo root is derived from
this file's own location, never from a caller-supplied path.

The authorizing act (FR29(b), AR-9 — the consumer-facing statement this
shipped module carries so a consumer receiving the gate is not left to guess
what it does). Applying the `needs-ai` label (or whatever `--label` names) to
an issue, from your own GitHub account, STARTS AUTONOMOUS WORK ON THAT
ISSUE. This INCLUDES issues you did not author and whose content you do not
control — the gate never treats an issue's body or its labels as evidence of
who filed it. The act does NOT make the issue's author trusted, and it does
NOT make the issue's body trustworthy: the gate never reads an issue's body,
and requester trust and live authorization are evaluated independently of
one another. Two preconditions this gate requires and neither is shipped nor
generated by an installer: (1) `.github/CODEOWNERS` must name at least one
INDIVIDUAL human GitHub handle — a file naming only `org/team` patterns
confers no authorization authority and the gate refuses to run rather than
silently authorize nothing forever; (2) `scripts/framework/machine-accounts.env`
must exist, naming `BOT_WORKER_USERNAME`, `BOT_OVERSEER_USERNAME`,
`BOT_HUMAN_USERNAME` and `COPILOT_BOT_LOGIN` — its absence stops work
selection entirely. A CLI-only operator with no browser session is not
stranded: the authorizing act may be performed with a personal-access-token
`gh` invocation under your own login (`gh issue edit <n> --add-label
needs-ai`, after removing it first if it is already present, since a
re-applied label produces no new event to verify).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

from scripts.framework.requester_trust import (
    RequesterVerdict,
    codeowners_humans,
    fetch_collaborators,
    load_bot_accounts,
    load_trusted_apps,
    load_trusted_requesters,
    load_trusted_set,
    machine_accounts_file_absent,
    requester_verdict,
    verify_codeowner_actor,
)

# ---------------------------------------------------------------------------
# Module constants (§2.2.1, §5 — NOT flags, deliberately: AD-13)
# ---------------------------------------------------------------------------

EXCLUDED_LABELS = ("needs-human",)  # the ADR-1604 AD-5 exclusion landing site
LIST_PAGE_BOUND = 5  # 500 records (AM-22 / AF-8)
EVENTS_PAGE_BOUND = 10  # 1000 events (AM-5)

_DEFAULT_MAX_CANDIDATES = 5
_DEFAULT_MAX_API_REQUESTS = 100

_PRIORITY_NAMES = ("critical", "high", "medium", "low")
_PRIORITY_LABELS = tuple(f"priority:{name}" for name in _PRIORITY_NAMES)

_REPO_RE = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")

# The repo root is derived from this file's own location — never from a flag
# (AD-13). Module-level so tests can monkeypatch it to a throwaway tree.
_REPO_ROOT = Path(__file__).resolve().parents[2]

_GH_SUBPROCESS_TIMEOUT_SECONDS = 30


# ---------------------------------------------------------------------------
# Argument parsing (§2.2 — EXACTLY FIVE FLAGS)
# ---------------------------------------------------------------------------


def _positive_int(value: str) -> int:
    if not re.fullmatch(r"[0-9]+", value):
        raise argparse.ArgumentTypeError(
            f"{value!r} is not a positive integer (an unsubstituted "
            "@@MILESTONE_NUMBER@@ must fail closed, never be coerced)"
        )
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError(f"{value!r} is not a positive integer")
    return parsed


def _repo_slug(value: str) -> str:
    if not _REPO_RE.match(value):
        raise argparse.ArgumentTypeError(f"{value!r} is not a valid owner/repo slug")
    return value


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="select_work_candidates",
        description="Query + trust + authorization + ordering. The only way "
        "work candidates are produced (AD-3).",
    )
    parser.add_argument("--repo", required=True, type=_repo_slug)
    parser.add_argument("--milestone", required=True, type=_positive_int)
    parser.add_argument("--label", default="needs-ai")
    parser.add_argument("--max-candidates", type=int, default=_DEFAULT_MAX_CANDIDATES)
    parser.add_argument("--max-api-requests", type=int, default=_DEFAULT_MAX_API_REQUESTS)
    return parser


# ---------------------------------------------------------------------------
# The per-cycle API request budget (§2.2.1's counter)
# ---------------------------------------------------------------------------


class _Budget:
    """`api_requests <= effective_ceiling` holds by construction: the stop
    test runs BEFORE every request, and the counter increments AFTER a
    request returns, successfully or not (§2.2.1)."""

    def __init__(self, ceiling: int):
        self.ceiling = ceiling
        self.spent = 0

    def refuse(self) -> bool:
        return self.spent >= self.ceiling

    def record(self) -> None:
        self.spent += 1


# ---------------------------------------------------------------------------
# The per-page fetch rule (§1.4, revision 8 / RP5-1) — shared by Step C's
# issue list and D5.2's events fetch.
# ---------------------------------------------------------------------------


class _GhFailure(Exception):
    """One page's `gh api` invocation could not be parsed."""


def _run_gh(endpoint: str) -> Any:
    """Issue exactly ONE `gh api <endpoint>` GET and return parsed JSON.

    Shells out directly with `subprocess.run`, following the precedent
    already set in this directory by `require_human_approval.py`'s
    `reviews_from_gh` / `require_human_approval.py:_fetch_reviews` (§2.2's
    "GitHub access" note) — this module does NOT import
    `scripts.automation.lib.github._run_gh`, which sits on an unprotected
    surface (§1.1)."""
    try:
        result = subprocess.run(
            ["gh", "api", endpoint],
            capture_output=True,
            text=True,
            check=False,
            timeout=_GH_SUBPROCESS_TIMEOUT_SECONDS,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise _GhFailure(str(exc)) from exc
    if result.returncode != 0:
        raise _GhFailure(result.stderr.strip())
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise _GhFailure(str(exc)) from exc


@dataclass
class _FetchOutcome:
    records: list
    state: str  # "COMPLETE" | "BOUND-REACHED" | "REFUSED" | "FAILED"
    error: str = ""


def _fetch_pages(
    endpoint_for_page: Callable[[int], str], page_bound: int, budget: _Budget
) -> _FetchOutcome:
    """Fetch pages 1..page_bound, one `gh api` invocation each, per §1.4's
    per-page fetch rule. Before every page: (a) the page-bound range below
    already enforces the page bound; (b) the request ceiling's stop test.
    A page with fewer than 100 raw items ends the history (COMPLETE)."""
    collected: list = []
    for page in range(1, page_bound + 1):
        if budget.refuse():
            return _FetchOutcome(collected, "REFUSED")
        try:
            batch = _run_gh(endpoint_for_page(page))
        except _GhFailure as exc:
            budget.record()
            return _FetchOutcome(collected, "FAILED", str(exc))
        budget.record()
        if not isinstance(batch, list):
            return _FetchOutcome(collected, "FAILED", "non-list response")
        collected.extend(batch)
        if len(batch) < 100:
            return _FetchOutcome(collected, "COMPLETE")
    return _FetchOutcome(collected, "BOUND-REACHED")


# ---------------------------------------------------------------------------
# Step B — configuration (all fail-closed except tier resolution, AM-31)
# ---------------------------------------------------------------------------


class _ConfigFailure(Exception):
    def __init__(self, token: str, remediation: str = ""):
        super().__init__(token)
        self.token = token
        self.remediation = remediation


@dataclass
class _Configuration:
    trusted_set: Any
    codeowners: set
    bots: set
    tier_degraded: bool
    tier_count: int
    collaborator_bound_reached: bool


def _load_configuration(repo_root: str, repo: str, budget: _Budget) -> _Configuration:
    """Step B, in order (§2.3): bots, codeowners, apps, roster, then the
    LAZY, conditional collaborator fetch (H3, §1.3.2). Raises
    `_ConfigFailure` for every fail-closed row; tier resolution never raises
    (AM-31: a degraded tier resolution can only shrink the trusted set)."""
    # B1 — bots.
    bots = load_bot_accounts(repo_root)
    if not bots:
        if machine_accounts_file_absent(repo_root):
            raise _ConfigFailure(
                "machine-accounts-file-absent",
                "this file is required by the work-selection gate, is not "
                "shipped by HOS and is not produced by the installer; create "
                "it with BOT_WORKER_USERNAME, BOT_OVERSEER_USERNAME, "
                "BOT_HUMAN_USERNAME and COPILOT_BOT_LOGIN",
            )
        raise _ConfigFailure(
            "bot-accounts-empty",
            "no bot accounts resolved; the gate cannot distinguish a bot "
            "from a human and refuses to run",
        )

    # B2 — CODEOWNERS. Three distinct facts, three distinct tokens (AM-34).
    codeowners_path = Path(repo_root) / ".github" / "CODEOWNERS"
    if not codeowners_path.is_file():
        raise _ConfigFailure(
            "codeowners-file-absent",
            "create `.github/CODEOWNERS` naming at least one individual "
            "GitHub user who may authorize work",
        )
    try:
        codeowners = codeowners_humans(repo_root)
    except OSError as exc:
        raise _ConfigFailure(
            "codeowners-unreadable",
            "the file exists but could not be read; check permissions",
        ) from exc
    if not codeowners:
        raise _ConfigFailure(
            "codeowners-no-individual-human",
            "this file is valid but lists only team handles; team handles "
            "do not confer authorization authority. Add at least one "
            "individual user handle.",
        )

    # B3 — apps.
    apps = load_trusted_apps(repo_root)
    if not apps:
        if machine_accounts_file_absent(repo_root):
            raise _ConfigFailure(
                "machine-accounts-file-absent",
                "this file is required by the work-selection gate, is not "
                "shipped by HOS and is not produced by the installer; create "
                "it with BOT_WORKER_USERNAME, BOT_OVERSEER_USERNAME, "
                "BOT_HUMAN_USERNAME and COPILOT_BOT_LOGIN",
            )
        raise _ConfigFailure("trusted-apps-empty", "no HOS App identities resolved")

    # B4 — roster.
    try:
        policy = load_trusted_requesters(repo_root)
    except OSError as exc:
        raise _ConfigFailure("roster-unreadable") from exc

    # B5 — LAZY, conditional collaborator fetch (H3). Zero cost when no tier
    # is listed. Any failure is completeness-affecting, never security
    # (AM-31): it can only ever SHRINK the trusted set.
    collaborators = None
    tier_degraded = False
    collaborator_bound_reached = False
    if policy.tiers:
        before = budget.spent
        collaborators, _ = fetch_collaborators(repo, budget.refuse, budget.record)
        delta = budget.spent - before
        if collaborators is None:
            # A ceiling refusal (ANY page, including the first) is quiet by
            # construction (fetch_collaborators never prints). A genuine
            # transport/parse failure is not. `fetch_collaborators`'s
            # contract does not expose which case fired directly, so this
            # is inferred: `delta == 0` is unambiguous (page 1 itself was
            # refused before any request); `delta > 0` with the ceiling now
            # exhausted is read as "the ceiling caused this" too. The one
            # imprecision this leaves — a genuine failure landing on the
            # exact request that also exhausts the ceiling — fails toward
            # silence on a completeness-only signal, never toward a security
            # claim, which is the same class of accepted imprecision §1.4
            # rule 4(a) states for the events-fetch clamp.
            if delta == 0 or budget.refuse():
                pass
            else:
                tier_degraded = True
        elif delta == 3 and len(collaborators) == 300:
            # COLLABORATOR_PAGE_BOUND (3) pages, all full (300 collaborators
            # returned) — the exact-multiple imprecision §1.4 rule 4(a)
            # accepts elsewhere: indistinguishable from a repo with exactly
            # 300 collaborators, and it fails safe (an under-resolved tier
            # only shrinks who is trusted).
            collaborator_bound_reached = True

    trusted_set = load_trusted_set(repo_root, collaborators=collaborators)
    return _Configuration(
        trusted_set=trusted_set,
        codeowners=codeowners,
        bots=bots,
        tier_degraded=tier_degraded,
        tier_count=len(policy.tiers),
        collaborator_bound_reached=collaborator_bound_reached,
    )


# ---------------------------------------------------------------------------
# Step D1/D2 — free filters
# ---------------------------------------------------------------------------


def _label_names(record: dict) -> set:
    return {label.get("name") for label in (record.get("labels") or []) if isinstance(label, dict)}


def _apply_free_filters(raw_records: list) -> list:
    """D1 (drop pull_request records) and D2 (drop EXCLUDED_LABELS), applied
    BEFORE ranking so the ranked set and the eligible universe are drawn
    from the same population (§2.3 D5.1 limb (c))."""
    kept = []
    for record in raw_records:
        if not isinstance(record, dict):
            continue
        if record.get("pull_request"):
            continue
        if _label_names(record) & set(EXCLUDED_LABELS):
            continue
        kept.append(record)
    return kept


def _rank(record: dict) -> int:
    names = _label_names(record)
    for rank, label in enumerate(_PRIORITY_LABELS):
        if label in names:
            return rank
    return 3


@dataclass
class _Candidate:
    number: int
    title: str
    rank: int
    verdict: RequesterVerdict
    record: dict


# ---------------------------------------------------------------------------
# Step D5 — the ranked walk
# ---------------------------------------------------------------------------


@dataclass
class _WalkResult:
    eligible: list = field(default_factory=list)  # _Candidate, in ADMISSION order
    authorized: dict = field(default_factory=dict)  # issue number -> actor login
    gated_reasons: Counter = field(default_factory=Counter)
    gated_issue_numbers: list = field(default_factory=list)
    query_failed_issues: list = field(default_factory=list)
    unevaluated_sufficient: int = 0
    unevaluated_cost_ceiling: int = 0
    cost_ceiling_named_issue: Optional[int] = None
    stopped: bool = False
    warn_lines: list = field(default_factory=list)


def _walk(
    walk_order: list,
    repo: str,
    label: str,
    codeowners: set,
    bots: set,
    budget: _Budget,
    max_candidates: int,
) -> _WalkResult:
    result = _WalkResult()
    i = 0
    n = len(walk_order)
    while i < n:
        cand = walk_order[i]
        if len(result.eligible) >= max_candidates:
            result.unevaluated_sufficient += n - i
            result.stopped = True
            return result
        if cand.verdict.trusted:
            result.eligible.append(cand)
            i += 1
            continue
        if budget.refuse():
            result.unevaluated_cost_ceiling += n - i
            result.stopped = True
            return result
        endpoint = lambda page, num=cand.number: (
            f"repos/{repo}/issues/{num}/events?per_page=100&page={page}"
        )
        outcome = _fetch_pages(endpoint, EVENTS_PAGE_BOUND, budget)
        if outcome.state == "FAILED":
            result.query_failed_issues.append(cand.number)
            result.warn_lines.append(f"WARN unevaluated:query-failed issue=#{cand.number}")
            i += 1
            continue
        actor = verify_codeowner_actor(outcome.records, codeowners, bots, label)
        if outcome.state == "REFUSED":
            if actor is not None:
                result.eligible.append(cand)
                result.authorized[cand.number] = actor
                i += 1
                continue
            # The clamp bit (§1.4 rule 4): a full last page, the next page
            # refused, no match. This record and everything after it are
            # unevaluated:cost-ceiling — the walk ends COMPLETELY here.
            result.cost_ceiling_named_issue = cand.number
            result.unevaluated_cost_ceiling += n - i
            result.stopped = True
            return result
        # COMPLETE or BOUND-REACHED: a determination.
        if actor is not None:
            result.eligible.append(cand)
            result.authorized[cand.number] = actor
        else:
            if outcome.state == "BOUND-REACHED":
                result.warn_lines.append(f"WARN events-page-bound-reached issue=#{cand.number}")
            result.gated_reasons["no-codeowner-actor"] += 1
            result.gated_issue_numbers.append(cand.number)
        i += 1
    return result


# ---------------------------------------------------------------------------
# Step F — the stderr report
# ---------------------------------------------------------------------------


def _emit(*parts: str) -> None:
    print("select_work_candidates: " + " ".join(parts), file=sys.stderr)


def _report_and_exit(
    repo: str,
    milestone: int,
    scanned: int,
    eligible: list,
    gated_reasons: Counter,
    gated_issue_numbers: list,
    authorized: dict,
    unevaluated_sufficient: int,
    unevaluated_cost_ceiling: int,
    cost_ceiling_named_issue: Optional[int],
    query_failed_issues: list,
    list_truncated: bool,
    tier_degraded: bool,
    tier_count: int,
    collaborator_bound_reached: bool,
    api_requests: int,
    walk_warn_lines: list,
    ceiling_refused_at_list: bool = False,
) -> int:
    gated_count = sum(gated_reasons.values())
    evaluated = len(eligible) + gated_count
    unevaluated = unevaluated_sufficient + unevaluated_cost_ceiling + len(query_failed_issues)
    # A Step C page refused by the request ceiling is, on its own, a bound
    # that truncated the candidate set (§2.3 Step C's REFUSED state;
    # revision 8) — complete=no even when nothing was fetched at all
    # (N=0 at --max-api-requests 0). This is forced independently of the
    # unevaluated/list-truncated/tier-degraded computation below, which
    # would otherwise read an empty, unreached set as trivially complete.
    complete = (
        unevaluated == 0
        and not list_truncated
        and not tier_degraded
        and not ceiling_refused_at_list
    )

    for line in walk_warn_lines:
        _emit(line)

    if unevaluated > 0 or list_truncated:
        _emit(
            f"UNEVALUATED {unevaluated} of {scanned} records were not evaluated:",
            f"unevaluated:sufficient={unevaluated_sufficient}",
            f"unevaluated:cost-ceiling={unevaluated_cost_ceiling}",
            f"unevaluated:query-failed={len(query_failed_issues)}",
            f"unevaluated:list-truncated={'yes' if list_truncated else 'no'}",
        )
    for issue in query_failed_issues:
        _emit(f"WARN unevaluated:query-failed issue=#{issue}")
    if cost_ceiling_named_issue is not None:
        _emit(f"unevaluated:cost-ceiling issue=#{cost_ceiling_named_issue}")
        _emit(f"budget-clamped-events-fetch issue=#{cost_ceiling_named_issue}")

    for issue, actor in sorted(authorized.items()):
        _emit(f"AUTHORIZED issue=#{issue} actor={actor} via=labeled")

    if list_truncated:
        _emit(
            f"WARN candidate-list-truncated pages={LIST_PAGE_BOUND} —",
            "at least",
            f"{LIST_PAGE_BOUND * 100} records matched; the total is UNKNOWN",
        )
    if tier_degraded:
        _emit(f"WARN tier-resolution-failed tiers={tier_count}")
    if collaborator_bound_reached:
        _emit("WARN collaborator-page-bound-reached pages=3")

    if not eligible and gated_count > 0:
        _emit(
            f"ALL-CANDIDATES-GATED {gated_count} of {scanned} in-milestone",
            "issues are held for human authorization",
        )
        reasons_str = " ".join(f"{tok}={cnt}" for tok, cnt in sorted(gated_reasons.items()))
        _emit(f"ALL-CANDIDATES-GATED reasons: {reasons_str}")
        shown = gated_issue_numbers[:20]
        more = len(gated_issue_numbers) - len(shown)
        issues_str = " ".join(f"#{n}" for n in shown)
        if more > 0:
            issues_str += f" (+{more} more)"
        _emit(f"ALL-CANDIDATES-GATED issues: {issues_str}")
        if not complete:
            _emit(
                f"ALL-CANDIDATES-GATED INCOMPLETE — {unevaluated} further",
                "records were not evaluated (see UNEVALUATED above); this",
                "count is a FLOOR",
            )

    _emit(
        f"repo={repo}",
        f"milestone={milestone}",
        f"scanned={scanned}",
        f"evaluated={evaluated}",
        f"eligible={len(eligible)}",
        f"authorized={len(authorized)}",
        f"gated={gated_count}",
        f"unevaluated={unevaluated}",
        f"api_requests={api_requests}",
        f"complete={'yes' if complete else 'no'}",
    )

    if complete is False and not eligible:
        return 3
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv: Optional[list] = None) -> int:
    parser = _build_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:
        # argparse's own usage-error exit is 2, which is consistent: a
        # malformed invocation is a fail-closed condition (§2.2).
        return exc.code if isinstance(exc.code, int) else 2

    effective_max_candidates = min(_DEFAULT_MAX_CANDIDATES, max(1, args.max_candidates))
    effective_max_api_requests = min(_DEFAULT_MAX_API_REQUESTS, max(0, args.max_api_requests))

    repo_root = str(_REPO_ROOT)
    budget = _Budget(effective_max_api_requests)

    try:
        config = _load_configuration(repo_root, args.repo, budget)
    except _ConfigFailure as exc:
        _emit(exc.token)
        if exc.remediation:
            _emit(exc.remediation)
        return 2
    except Exception:  # noqa: BLE001 — Step B's own catch-all (§2.3 Step B item 7)
        _emit("config-error")
        return 2

    # Step C — the paginated list query.
    def list_endpoint(page: int) -> str:
        return (
            f"repos/{args.repo}/issues?state=open&milestone={args.milestone}"
            f"&labels={args.label}&per_page=100&page={page}"
        )

    outcome = _fetch_pages(list_endpoint, LIST_PAGE_BOUND, budget)
    if outcome.state == "FAILED":
        _emit("list-query-failed")
        return 2

    candidates_raw = _apply_free_filters(outcome.records)
    scanned = len(candidates_raw)
    list_truncated = outcome.state == "BOUND-REACHED"
    ceiling_refused_at_list = outcome.state == "REFUSED"

    if ceiling_refused_at_list:
        # "The gate does not walk a partial list." Nothing is admitted.
        # Every fetched-and-filtered record counts as unevaluated:cost-ceiling
        # (§2.3 Step C REFUSED state). No WARN — the ceiling is routine.
        return _report_and_exit(
            repo=args.repo,
            milestone=args.milestone,
            scanned=scanned,
            eligible=[],
            gated_reasons=Counter(),
            gated_issue_numbers=[],
            authorized={},
            unevaluated_sufficient=0,
            unevaluated_cost_ceiling=scanned,
            cost_ceiling_named_issue=None,
            query_failed_issues=[],
            list_truncated=False,
            tier_degraded=config.tier_degraded,
            tier_count=config.tier_count,
            collaborator_bound_reached=config.collaborator_bound_reached,
            api_requests=budget.spent,
            walk_warn_lines=[],
            ceiling_refused_at_list=True,
        )

    # D3/D4/D-rank — free, computed over the whole (post-D1/D2) set.
    candidate_states = [
        _Candidate(
            number=r.get("number"),
            title=r.get("title") or "",
            rank=_rank(r),
            verdict=requester_verdict(r, config.trusted_set),
            record=r,
        )
        for r in candidates_raw
    ]
    walk_order = sorted(candidate_states, key=lambda c: (c.rank, -c.number))

    walk_result = _walk(
        walk_order,
        repo=args.repo,
        label=args.label,
        codeowners=config.codeowners,
        bots=config.bots,
        budget=budget,
        max_candidates=effective_max_candidates,
    )

    emit_order = sorted(walk_result.eligible, key=lambda c: (c.rank, c.number))
    for c in emit_order:
        print(f"#{c.number} [{_PRIORITY_NAMES[c.rank]}] {c.title}")

    return _report_and_exit(
        repo=args.repo,
        milestone=args.milestone,
        scanned=scanned,
        eligible=walk_result.eligible,
        gated_reasons=walk_result.gated_reasons,
        gated_issue_numbers=walk_result.gated_issue_numbers,
        authorized=walk_result.authorized,
        unevaluated_sufficient=walk_result.unevaluated_sufficient,
        unevaluated_cost_ceiling=walk_result.unevaluated_cost_ceiling,
        cost_ceiling_named_issue=walk_result.cost_ceiling_named_issue,
        query_failed_issues=walk_result.query_failed_issues,
        list_truncated=list_truncated,
        tier_degraded=config.tier_degraded,
        tier_count=config.tier_count,
        collaborator_bound_reached=config.collaborator_bound_reached,
        api_requests=budget.spent,
        walk_warn_lines=walk_result.warn_lines,
    )


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
